package matteroverdrive.world;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.mojang.serialization.JsonOps;
import net.minecraft.world.level.block.state.BlockState;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Base64;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * A 1.7.10 MOImageGen building as generated by tools/gen_resources.py from the 1.7.10 images
 * ({@code data/matteroverdrive/mo_buildings/<id>.json}): a palette of block states (1.7.10 metadata already resolved)
 * and one palette index per block, 0 meaning "leave the world as it is".
 *
 * @param entries palette, index 1.. in {@link #index}
 */
public record BuildingTemplate(int width, int depth, int height, List<Entry> entries, byte[][] layers) {
    /**
     * One 1.7.10 BlockMapping: several states are picked per block when {@code noise}, otherwise once per building
     * for all blocks of the same colour ({@code group}).
     */
    public record Entry(List<BlockState> states, boolean noise, int group, List<String> specials) {
        public boolean has(String special) {
            return specials.contains(special);
        }
    }

    private static final Map<String, BuildingTemplate> CACHE = new ConcurrentHashMap<>();

    public static BuildingTemplate get(String id) {
        return CACHE.computeIfAbsent(id, BuildingTemplate::load);
    }

    /** Palette entry at a building-local position, or null. */
    public Entry at(int x, int y, int z) {
        int index = layers[y][z * width + x] & 0xFF;
        return index == 0 ? null : entries.get(index - 1);
    }

    private static BuildingTemplate load(String id) {
        String path = "/data/matteroverdrive/mo_buildings/" + id + ".json";
        try (InputStream in = BuildingTemplate.class.getResourceAsStream(path)) {
            if (in == null) throw new IllegalStateException("Missing building template " + path);
            JsonObject json = JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8)).getAsJsonObject();
            List<Entry> entries = new ArrayList<>();
            for (JsonElement e : json.getAsJsonArray("palette")) {
                JsonObject o = e.getAsJsonObject();
                List<BlockState> states = new ArrayList<>();
                for (JsonElement s : o.getAsJsonArray("states")) {
                    states.add(BlockState.CODEC.parse(JsonOps.INSTANCE, s).getOrThrow(msg -> new IllegalStateException(id + ": " + msg)));
                }
                List<String> specials = new ArrayList<>();
                o.getAsJsonArray("specials").forEach(s -> specials.add(s.getAsString()));
                entries.add(new Entry(List.copyOf(states), o.get("noise").getAsBoolean(), o.get("group").getAsInt(), List.copyOf(specials)));
            }
            JsonArray layerData = json.getAsJsonArray("layers");
            byte[][] layers = new byte[layerData.size()][];
            for (int i = 0; i < layers.length; i++) {
                layers[i] = Base64.getDecoder().decode(layerData.get(i).getAsString());
            }
            return new BuildingTemplate(json.get("width").getAsInt(), json.get("depth").getAsInt(), json.get("height").getAsInt(),
                    List.copyOf(entries), layers);
        } catch (IOException e) {
            throw new IllegalStateException("Can't read building template " + path, e);
        }
    }
}
