package matteroverdrive.starmap;

/** 1.7.10 PlanetStatType. */
public enum PlanetStatType {
    FLEET_SIZE, BUILDINGS_SIZE, SHIP_BUILD_SPEED, BUILDING_BUILD_SPEED, MATTER_STORAGE, ENERGY_PRODUCTION, POPULATION_COUNT, HAPPINESS,
    MATTER_PRODUCTION
}
